version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-spring-cloud
    ports:
      - 5672:5672
      - 15672:15672

  mariadb:
    image: mariadb
    container_name: mariadb-spring-cloud
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret

